fix(authentication): Add client_secret in auth method
ekeih/libtado pull request #3
Opened 2019-01-23 20:15 UTC by germainlefebvre4

2019-02-02 00:15 UTC, ekeih requested changes
I added a few comments.

FYI: I stumbled accross https://github.com/chrism0dwk/PyTado/issues/6.

2019-02-02 00:15 UTC, ekeih commented on README.md
> +You can download officiel library with `pip install libtado`.
```suggestion
You can download official library with `pip install libtado`.
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +But ifyou want to benefits with improvements for API v2 you will need to download this library.
```suggestion
But because I do not own a Tado anymore you may want to use a fork of libtado instead. For example you can install the fork that is currently (February 2019) maintained and improved by @germainlefebvre4. Please note that I do not monitor or verify changes of this repository. Please check the source yourself.
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +*Your `CLIENT_SECRET` must keep secret.*
```suggestion
*Your `CLIENT_SECRET` must be kept secret.*
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +Download the repository. You can work inside it. Beware the examples considere they can acces to the file `./libtado/api.py`.
```suggestion
Download the repository. You can work inside it. Beware that the examples assume that they can access the file `./libtado/api.py`.
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +Now you can call it in your Pyhton script !
```suggestion
Now you can call it in your Pyhton script!
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +An script example is provided in the repository as `example.py`.
```suggestion
An example script is provided in the repository as `example.py`.
```

2019-02-02 00:15 UTC, ekeih commented on README.md
> +It show you haw to use the library and expose some structured responses.
```suggestion
It shows you how to use the library and expose some structured responses. A more detailed example is available in `libtado/__main__.py`.
```

2019-02-03 15:34 UTC, germainlefebvre4 commented
Thank you for the link. This will be very useful for the ,ext steps ;)

2019-02-13 11:39 UTC, ekeih approved these changes

2019-02-13 11:41 UTC, merged

2019-02-13 13:46 UTC, ekeih commented
@germainlefebvre4 Thanks for contributing :) I published a 3.0.0 on [PyPi](https://pypi.org/project/libtado/).